**Importar libreria numpy**

In [2]:
import numpy as np

**Array es un conjunto de datos**

In [8]:
lista = ([[1,2,3],[4,5,6],[7,8,9]])
np.array (lista)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
lista = [1,2,3,4,5,6,7,8]

In [10]:
vector = np.array(lista)

In [11]:
vector

array([1, 2, 3, 4, 5, 6, 7, 8])

In [12]:
vector.reshape((2,4))

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [13]:
matriz = vector.reshape((2,4))

In [15]:
matriz

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])